# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-19 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_app', '0006_remove_show_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
